// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DeleteResultAPI is an autogenerated mock type for the DeleteResultAPI type
type DeleteResultAPI struct {
	mock.Mock
}

type mockConstructorTestingTNewDeleteResultAPI interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeleteResultAPI creates a new instance of DeleteResultAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeleteResultAPI(t mockConstructorTestingTNewDeleteResultAPI) *DeleteResultAPI {
	mock := &DeleteResultAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
